<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>WindowsToolbox.App</RootNamespace>
    <AssemblyName>Windows工具箱</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsToolbox.Modules.KeepAwake\WindowsToolbox.Modules.KeepAwake.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.LockInspector\WindowsToolbox.Modules.LockInspector.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Core\WindowsToolbox.Core.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.InstalledApps\WindowsToolbox.Modules.InstalledApps.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.NetworkTraffic\WindowsToolbox.Modules.NetworkTraffic.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.Shutdown\WindowsToolbox.Modules.Shutdown.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.ClipboardPlus\WindowsToolbox.Modules.ClipboardPlus.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.TextTools\WindowsToolbox.Modules.TextTools.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.FileTools\WindowsToolbox.Modules.FileTools.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.QuickLaunch\WindowsToolbox.Modules.QuickLaunch.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.WindowTools\WindowsToolbox.Modules.WindowTools.csproj" />
    <ProjectReference Include="..\WindowsToolbox.Modules.Utilities\WindowsToolbox.Modules.Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>
</Project>
