<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WindowsToolbox.Modules.NetworkTraffic</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsToolbox.Core\WindowsToolbox.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.7" />
  </ItemGroup>
</Project>
